export { default as logo } from './logo.vue'
export { default as home } from './home.vue'
export { default as logout } from './logout.vue'
export { default as star } from './star.vue'
export { default as fork } from './fork.vue'
export { default as arrow } from './arrow.vue'
export { default as spinner } from './spinner.vue'
export { default as cross } from './cross.vue'
